/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SgCard {
        "cardTitle": any;
        "speakers": any;
        "time": any;
    }
    interface SgCardList {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSgCardElement extends Components.SgCard, HTMLStencilElement {
    }
    var HTMLSgCardElement: {
        prototype: HTMLSgCardElement;
        new (): HTMLSgCardElement;
    };
    interface HTMLSgCardListElement extends Components.SgCardList, HTMLStencilElement {
    }
    var HTMLSgCardListElement: {
        prototype: HTMLSgCardListElement;
        new (): HTMLSgCardListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sg-card": HTMLSgCardElement;
        "sg-card-list": HTMLSgCardListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SgCard {
        "cardTitle"?: any;
        "speakers"?: any;
        "time"?: any;
    }
    interface SgCardList {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sg-card": SgCard;
        "sg-card-list": SgCardList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sg-card": LocalJSX.SgCard & JSXBase.HTMLAttributes<HTMLSgCardElement>;
            "sg-card-list": LocalJSX.SgCardList & JSXBase.HTMLAttributes<HTMLSgCardListElement>;
        }
    }
}
